# Generated by Django 6.1.1 on 2026-10-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='role',
            new_name='roll',
        ),
    ]
